If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [20]:
multiples = []
for num in range(1,1000):
    if num%3 == 0 or num%5 == 0:
        multiples.append(num)
#print(multiples)
sum(multiples)

233168

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [22]:
fibonacci = [1,2]
even_fibonacci = []
for i in range(1,32):
    b=fibonacci[i-1]+fibonacci[i]
    fibonacci.append(b)

for num in fibonacci:
    if num%2 == 0 and num<4000000:
        even_fibonacci.append(num)
#print(fibonacci)
print(even_fibonacci)
sum(even_fibonacci)

[2, 8, 34, 144, 610, 2584, 10946, 46368, 196418, 832040, 3524578]

4613732

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [53]:
import math
num = 13195
primes = []

for i in range(2, int(num**0.5)+1):
    if num%i == 0:
        primes.append(i)
print(primes)

for j in primes:
    if j > 2 and j%2==0:
        primes.remove(j)
print(primes)

for k in primes:
    if k > 5 and k%5==0:
        primes.remove(k)
print(primes)

[5, 7, 13, 29, 35, 65, 91]
[5, 7, 13, 29, 35, 65, 91]
[5, 7, 13, 29, 65, 91]

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [23]:
a = [number for number in range(1,1000)]
b = [number for number in range(1,1000)]
num_list = []
reversed_nums = []
palindrom_list = []

for x in a:
    for y in b:
        value = x*y
        if value > 11:
            num_list.append(value)
print(num_list[:30])
#print(len(num_list))

for num in num_list:
    num = str(num)[::-1]
    reversed_nums.append(int(num))
print(reversed_nums[:30])
#print(len(reversed_nums))

zipped = zip(num_list, reversed_nums)
pairs = list(zipped)

for i, j in pairs:
    if i == j:
        palindrom_list.append(i)
#print(set(palindrom_list))
print(max(palindrom_list))

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]
[21, 31, 41, 51, 61, 71, 81, 91, 2, 12, 22, 32, 42, 52, 62, 72, 82, 92, 3, 13, 23, 33, 43, 53, 63, 73, 83, 93, 4, 14]
906609

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [ ]:
number = 500000000
smallest_num = []

for i in range(50000000,number):
  if all(i%num == 0 for num in range(1,21)):
    smallest_num.append(i)

print(smallest_num)

The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

In [ ]:
natural_nums = list(range(1,101))
int_nn = []
sq_nn = []

for num in natural_nums:
  int_nn.append(int(num))

for num in int_nn:
  sq_nn.append(num**2)

print(natural_nums)
print(int_nn)
print(sq_nn)
print(sum(int_nn)**2-sum(sq_nn))

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?